all: # 全ホスト定義
  children: # グループ定義
    db: # db グループ
      hosts: # ホスト定義
        localhost: # ローカルホストを指定
          ansible_connection: local # ローカル接続を使用
    app: # app グループ
      hosts: # ホスト定義
        localhost: # ローカルホストを指定
          ansible_connection: local # ローカル接続を使用
    web: # web グループ
      hosts: # ホスト定義
        localhost: # ローカルホストを指定
          ansible_connection: local # ローカル接続を使用
